language: java
jdk: oraclejdk8
sudo: required

before_script:
    - chmod +x gradlew

jobs:
  include:
    - stage: build
      script: ./gradlew build -i
    - stage: report
      script: ./gradlew jacocoTestReport && ./gradlew jacocoRootReport coveralls
